// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Command_Code int32

const (
	Command_PUT   Command_Code = 0
	Command_DUMP  Command_Code = 1
	Command_STATS Command_Code = 2
)

var Command_Code_name = map[int32]string{
	0: "PUT",
	1: "DUMP",
	2: "STATS",
}

var Command_Code_value = map[string]int32{
	"PUT":   0,
	"DUMP":  1,
	"STATS": 2,
}

func (x Command_Code) String() string {
	return proto.EnumName(Command_Code_name, int32(x))
}

func (Command_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0, 0}
}

type Command struct {
	Cmd                  Command_Code `protobuf:"varint,1,opt,name=cmd,proto3,enum=main.Command_Code" json:"cmd,omitempty"`
	Val                  []int64      `protobuf:"varint,2,rep,packed,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetCmd() Command_Code {
	if m != nil {
		return m.Cmd
	}
	return Command_PUT
}

func (m *Command) GetVal() []int64 {
	if m != nil {
		return m.Val
	}
	return nil
}

type Dump struct {
	List                 []*Dump_ValAndCnt `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Dump) Reset()         { *m = Dump{} }
func (m *Dump) String() string { return proto.CompactTextString(m) }
func (*Dump) ProtoMessage()    {}
func (*Dump) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Dump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dump.Unmarshal(m, b)
}
func (m *Dump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dump.Marshal(b, m, deterministic)
}
func (m *Dump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dump.Merge(m, src)
}
func (m *Dump) XXX_Size() int {
	return xxx_messageInfo_Dump.Size(m)
}
func (m *Dump) XXX_DiscardUnknown() {
	xxx_messageInfo_Dump.DiscardUnknown(m)
}

var xxx_messageInfo_Dump proto.InternalMessageInfo

func (m *Dump) GetList() []*Dump_ValAndCnt {
	if m != nil {
		return m.List
	}
	return nil
}

type Dump_ValAndCnt struct {
	Val                  int64    `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	Cnt                  int32    `protobuf:"varint,2,opt,name=cnt,proto3" json:"cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dump_ValAndCnt) Reset()         { *m = Dump_ValAndCnt{} }
func (m *Dump_ValAndCnt) String() string { return proto.CompactTextString(m) }
func (*Dump_ValAndCnt) ProtoMessage()    {}
func (*Dump_ValAndCnt) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1, 0}
}

func (m *Dump_ValAndCnt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dump_ValAndCnt.Unmarshal(m, b)
}
func (m *Dump_ValAndCnt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dump_ValAndCnt.Marshal(b, m, deterministic)
}
func (m *Dump_ValAndCnt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dump_ValAndCnt.Merge(m, src)
}
func (m *Dump_ValAndCnt) XXX_Size() int {
	return xxx_messageInfo_Dump_ValAndCnt.Size(m)
}
func (m *Dump_ValAndCnt) XXX_DiscardUnknown() {
	xxx_messageInfo_Dump_ValAndCnt.DiscardUnknown(m)
}

var xxx_messageInfo_Dump_ValAndCnt proto.InternalMessageInfo

func (m *Dump_ValAndCnt) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *Dump_ValAndCnt) GetCnt() int32 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

type Stats struct {
	Received             int64    `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Stored               int64    `protobuf:"varint,2,opt,name=stored,proto3" json:"stored,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stats.Unmarshal(m, b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
}
func (m *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(m, src)
}
func (m *Stats) XXX_Size() int {
	return xxx_messageInfo_Stats.Size(m)
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetReceived() int64 {
	if m != nil {
		return m.Received
	}
	return 0
}

func (m *Stats) GetStored() int64 {
	if m != nil {
		return m.Stored
	}
	return 0
}

func init() {
	proto.RegisterEnum("main.Command_Code", Command_Code_name, Command_Code_value)
	proto.RegisterType((*Command)(nil), "main.Command")
	proto.RegisterType((*Dump)(nil), "main.Dump")
	proto.RegisterType((*Dump_ValAndCnt)(nil), "main.Dump.ValAndCnt")
	proto.RegisterType((*Stats)(nil), "main.Stats")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0x3f, 0x6b, 0xc3, 0x30,
	0x14, 0xc4, 0x6b, 0x4b, 0xce, 0x9f, 0x57, 0x08, 0xe6, 0x51, 0x8a, 0xc9, 0x64, 0x4c, 0x06, 0x4d,
	0x2a, 0xa4, 0x63, 0xa7, 0xe0, 0xac, 0x85, 0x20, 0x3b, 0xdd, 0x55, 0x4b, 0x04, 0x83, 0x25, 0x05,
	0x4b, 0xcd, 0xe7, 0x2f, 0x72, 0x9c, 0x6c, 0x77, 0xf7, 0xd3, 0x71, 0xe2, 0xc1, 0xc6, 0x68, 0xef,
	0xe5, 0x45, 0x7b, 0x7e, 0x1d, 0x5d, 0x70, 0x48, 0x8d, 0xec, 0x6d, 0x75, 0x81, 0x65, 0xed, 0x8c,
	0x91, 0x56, 0xe1, 0x0e, 0x48, 0x67, 0x54, 0x91, 0x94, 0x09, 0xdb, 0xec, 0x91, 0x47, 0xcc, 0x67,
	0xc6, 0x6b, 0xa7, 0xb4, 0x88, 0x18, 0x73, 0x20, 0x37, 0x39, 0x14, 0x69, 0x49, 0x18, 0x11, 0x51,
	0x56, 0x3b, 0xa0, 0x11, 0xe3, 0x12, 0xc8, 0xe9, 0xdc, 0xe6, 0x2f, 0xb8, 0x02, 0x7a, 0x3c, 0x7f,
	0x9f, 0xf2, 0x04, 0xd7, 0x90, 0x35, 0xed, 0xa1, 0x6d, 0xf2, 0xb4, 0x92, 0x40, 0x8f, 0x7f, 0xe6,
	0x8a, 0x0c, 0xe8, 0xd0, 0xfb, 0x50, 0x24, 0x25, 0x61, 0xaf, 0xfb, 0xb7, 0xfb, 0x4c, 0x24, 0xfc,
	0x47, 0x0e, 0x07, 0xab, 0x6a, 0x1b, 0xc4, 0xf4, 0x62, 0xfb, 0x01, 0xeb, 0x67, 0xf4, 0x98, 0x8d,
	0x9f, 0xbb, 0xcf, 0xc6, 0xa4, 0xb3, 0xa1, 0x48, 0xcb, 0x84, 0x65, 0x22, 0xca, 0xea, 0x0b, 0xb2,
	0x26, 0xc8, 0xe0, 0x71, 0x0b, 0xab, 0x51, 0x77, 0xba, 0xbf, 0x69, 0x35, 0x37, 0x9e, 0x1e, 0xdf,
	0x61, 0xe1, 0x83, 0x1b, 0xb5, 0x9a, 0x9a, 0x44, 0xcc, 0xee, 0x77, 0x31, 0x5d, 0xe5, 0xf3, 0x3f,
	0x00, 0x00, 0xff, 0xff, 0x1c, 0x7a, 0xc0, 0x03, 0x27, 0x01, 0x00, 0x00,
}
